### ISSUE TITLE
Wetty install on RHEL 7 box fails

### ISSUE THREAD

**Issue by jeremyjpj0916** [butlerx/wetty#125]
Super excited to test this app, I attempted to install and see this:

```
#git clone https://github.com/krishnasrinivas/wetty
#cd wetty
#npm install
# node app.js -p 4545
module.js:478
    throw err;
    ^
Error: Cannot find module '../build/Release/pty.node'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/{MyUsername}/wetty/node_modules/pty.js/lib/pty.js:9:11)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
```

Ever seen this or have any ideas what would cause this?

**Comment by jeremyjpj0916** [comment]
Figured it out to anyone who comes across this:

Do
```
npm install -g node-gyp
cd /wetty/node_modules/pty.js/
make clean && node-gyp configure --release && node-gyp build
```

And boom started working 👍
