### ISSUE TITLE
[nodejs > 10.x] Outdated dependecies for using wetty

### ISSUE THREAD

**Issue by mirtouf** [butlerx/wetty#145]
Hi,

it seems several packages are outdated for use with nodejs 10.x (10.13.0 in my case) and lead to impossible manual installation like gulp:
```
yarn build
yarn run v1.12.3
$ gulp
gulp[2579]: ../src/node_contextify.cc:628:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
 1: 0x8daaa0 node::Abort() [gulp]
 2: 0x8dab75  [gulp]
 3: 0x90e2f7 node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [gulp]
 4: 0xb5e71b  [gulp]
 5: 0xb606b2 v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [gulp]
 6: 0x11ef2a55be1d 
Aborted
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Other packages needing updates (either for safety issues or for compatibility):
```
warning gulp-babel > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
warning gulp > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
warning gulp > vinyl-fs > graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
warning gulp > vinyl-fs > glob-stream > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-stream > glob > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-watcher > gaze > globule > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-watcher > gaze > globule > glob > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-watcher > gaze > globule > glob > graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
```

At the end, if trying to run wetty, the final error is:
```
/usr/bin/node bin/index.js
/usr/bin/node[3231]: ../src/node_file.cc:943:void node::fs::Stat(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `(argc) == (4)' failed.
 1: 0x8daaa0 node::Abort() [/usr/bin/node]
 2: 0x8dab75  [/usr/bin/node]
 3: 0x91abea  [/usr/bin/node]
 4: 0xb5faef  [/usr/bin/node]
 5: 0xb60659 v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/bin/node]
 6: 0x269e1ee5be1d 
Aborted
```
For the moment, versions up to nodejs v8.x are supported.

**Comment by butlerx** [comment]
Thanks for the report

**Comment by mirtouf** [comment]
I did a quick test by upgrading the packages version and run again yarn which run smoothly but when trying to build it failed:
```
yarn build
yarn run v1.12.3
$ gulp
assert.js:350
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/var/www/wetty/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/var/www/wetty/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/var/www/wetty/gulpfile.js:8:6)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Apollon77** [comment]
Also node 10.x is not working with wetty.js 0.5.1 (as I understood it) because it still want to install pty.js which is node 10 incompatible.

Seems that Github version do not match uploaded version

**Comment by Apollon77** [comment]
Verified! When I use the Guthub version on "krishnasrinivas/wetty" as dependency nod10 compat is there, so it seems that npm 0.5.1 is not in sync with github ... so maybe release 0.5.2 ? :-))

**Comment by butlerx** [comment]
unfortunately, I don't have access to the npm package. id need @krishnasrinivas to update the npm package

**Comment by mirtouf** [comment]
I tested master branch today and wetty built successfully with node v10.x

**Comment by butlerx** [comment]
thanks for the report
