### ISSUE TITLE
Installation fails with npm

### ISSUE THREAD

**Issue by abubakar-bilal** [butlerx/wetty#149]
Hi,

OS = MAC OS High Sierra 
NPM = 6.4.1
NODE = v11.5.0

I tried to run npm install -g wetty and I got this error

npm WARN deprecated connect@2.14.1: connect 2.x series is deprecated
npm WARN deprecated static-favicon@1.0.0: use serve-favicon module
/usr/local/bin/wetty -> /usr/local/lib/node_modules/wetty/bin/wetty.js

> pty.js@0.3.1 install /usr/local/lib/node_modules/wetty/node_modules/pty.js
> node-gyp rebuild

  CXX(target) Release/obj.target/pty/src/unix/pty.o
In file included from ../src/unix/pty.cc:20:
In file included from ../../nan/nan.h:190:
../../nan/nan_maybe_43_inl.h:88:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../src/unix/pty.cc:20:
In file included from ../../nan/nan.h:196:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:345:28: warning: 'New' is deprecated: Use Isolate* version [-Wdeprecated-declarations]
  return v8::StringObject::New(value).As<v8::StringObject>();
                           ^
/Users/abubakar/.node-gyp/11.5.0/include/node/v8.h:5242:37: note: 'New' has been explicitly marked deprecated here
                static Local<Value> New(Local<String> value));
                                    ^
In file included from ../src/unix/pty.cc:20:
../../nan/nan.h:816:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/abubakar/.node-gyp/11.5.0/include/node/node.h:172:50: note: 'MakeCallback' has been explicitly marked deprecated here
                NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                 ^
In file included from ../src/unix/pty.cc:20:
../../nan/nan.h:830:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/abubakar/.node-gyp/11.5.0/include/node/node.h:165:50: note: 'MakeCallback' has been explicitly marked deprecated here
                NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                 ^
In file included from ../src/unix/pty.cc:20:
../../nan/nan.h:844:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/abubakar/.node-gyp/11.5.0/include/node/node.h:158:50: note: 'MakeCallback' has been explicitly marked deprecated here
                NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                 ^
In file included from ../src/unix/pty.cc:20:
../../nan/nan.h:890:44: warning: 'ToString' is deprecated: Use maybe version [-Wdeprecated-declarations]
      v8::Local<v8::String> string = from->ToString();
                                           ^
/Users/abubakar/.node-gyp/11.5.0/include/node/v8.h:10248:22: note: 'ToString' has been explicitly marked deprecated here
Local<String> Value::ToString() const {
                     ^
In file included from ../src/unix/pty.cc:20:
../../nan/nan.h:900:27: warning: 'WriteUtf8' is deprecated: Use Isolate* version [-Wdeprecated-declarations]
        length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
                          ^
/Users/abubakar/.node-gyp/11.5.0/include/node/v8.h:2754:21: note: 'WriteUtf8' has been explicitly marked deprecated here
                int WriteUtf8(char* buffer, int length = -1,
                    ^
In file included from ../src/unix/pty.cc:20:
../../nan/nan.h:1457:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/abubakar/.node-gyp/11.5.0/include/node/node.h:172:50: note: 'MakeCallback' has been explicitly marked deprecated here
                NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                 ^
../src/unix/pty.cc:164:35: warning: 'ToString' is deprecated: Use maybe version [-Wdeprecated-declarations]
  String::Utf8Value file(info[0]->ToString());
                                  ^
/Users/abubakar/.node-gyp/11.5.0/include/node/v8.h:10248:22: note: 'ToString' has been explicitly marked deprecated here
Local<String> Value::ToString() const {
                     ^
../src/unix/pty.cc:164:21: warning: 'Utf8Value' is deprecated: Use Isolate version [-Wdeprecated-declarations]
  String::Utf8Value file(info[0]->ToString());
                    ^
/Users/abubakar/.node-gyp/11.5.0/include/node/v8.h:2992:28: note: 'Utf8Value' has been explicitly marked deprecated here
                  explicit Utf8Value(Local<v8::Value> obj));
                           ^
../src/unix/pty.cc:175:61: warning: 'ToString' is deprecated: Use maybe version [-Wdeprecated-declarations]
    String::Utf8Value arg(argv_->Get(Nan::New<Integer>(i))->ToString());
                                                            ^
/Users/abubakar/.node-gyp/11.5.0/include/node/v8.h:10248:22: note: 'ToString' has been explicitly marked deprecated here
Local<String> Value::ToString() const {
                     ^
../src/unix/pty.cc:175:23: warning: 'Utf8Value' is deprecated: Use Isolate version [-Wdeprecated-declarations]
    String::Utf8Value arg(argv_->Get(Nan::New<Integer>(i))->ToString());
                      ^
/Users/abubakar/.node-gyp/11.5.0/include/node/v8.h:2992:28: note: 'Utf8Value' has been explicitly marked deprecated here
                  explicit Utf8Value(Local<v8::Value> obj));
                           ^
../src/unix/pty.cc:186:61: warning: 'ToString' is deprecated: Use maybe version [-Wdeprecated-declarations]
    String::Utf8Value pair(env_->Get(Nan::New<Integer>(i))->ToString());
                                                            ^
/Users/abubakar/.node-gyp/11.5.0/include/node/v8.h:10248:22: note: 'ToString' has been explicitly marked deprecated here
Local<String> Value::ToString() const {
                     ^
../src/unix/pty.cc:186:23: warning: 'Utf8Value' is deprecated: Use Isolate version [-Wdeprecated-declarations]
    String::Utf8Value pair(env_->Get(Nan::New<Integer>(i))->ToString());
                      ^
/Users/abubakar/.node-gyp/11.5.0/include/node/v8.h:2992:28: note: 'Utf8Value' has been explicitly marked deprecated here
                  explicit Utf8Value(Local<v8::Value> obj));
                           ^
../src/unix/pty.cc:191:35: warning: 'ToString' is deprecated: Use maybe version [-Wdeprecated-declarations]
  String::Utf8Value cwd_(info[3]->ToString());
                                  ^
/Users/abubakar/.node-gyp/11.5.0/include/node/v8.h:10248:22: note: 'ToString' has been explicitly marked deprecated here
Local<String> Value::ToString() const {
                     ^
../src/unix/pty.cc:191:21: warning: 'Utf8Value' is deprecated: Use Isolate version [-Wdeprecated-declarations]
  String::Utf8Value cwd_(info[3]->ToString());
                    ^
/Users/abubakar/.node-gyp/11.5.0/include/node/v8.h:2992:28: note: 'Utf8Value' has been explicitly marked deprecated here
                  explicit Utf8Value(Local<v8::Value> obj));
                           ^
../src/unix/pty.cc:196:26: warning: 'IntegerValue' is deprecated: Use maybe version [-Wdeprecated-declarations]
  winp.ws_col = info[4]->IntegerValue();
                         ^
/Users/abubakar/.node-gyp/11.5.0/include/node/v8.h:2570:46: note: 'IntegerValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
                                             ^
../src/unix/pty.cc:197:26: warning: 'IntegerValue' is deprecated: Use maybe version [-Wdeprecated-declarations]
  winp.ws_row = info[5]->IntegerValue();
                         ^
/Users/abubakar/.node-gyp/11.5.0/include/node/v8.h:2570:46: note: 'IntegerValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
                                             ^
../src/unix/pty.cc:202:22: warning: 'IntegerValue' is deprecated: Use maybe version [-Wdeprecated-declarations]
  int uid = info[6]->IntegerValue();
                     ^
/Users/abubakar/.node-gyp/11.5.0/include/node/v8.h:2570:46: note: 'IntegerValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
                                             ^
../src/unix/pty.cc:203:22: warning: 'IntegerValue' is deprecated: Use maybe version [-Wdeprecated-declarations]
  int gid = info[7]->IntegerValue();
                     ^
/Users/abubakar/.node-gyp/11.5.0/include/node/v8.h:2570:46: note: 'IntegerValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
                                             ^
../src/unix/pty.cc:288:26: warning: 'IntegerValue' is deprecated: Use maybe version [-Wdeprecated-declarations]
  winp.ws_col = info[0]->IntegerValue();
                         ^
/Users/abubakar/.node-gyp/11.5.0/include/node/v8.h:2570:46: note: 'IntegerValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
                                             ^
../src/unix/pty.cc:289:26: warning: 'IntegerValue' is deprecated: Use maybe version [-Wdeprecated-declarations]
  winp.ws_row = info[1]->IntegerValue();
                         ^
/Users/abubakar/.node-gyp/11.5.0/include/node/v8.h:2570:46: note: 'IntegerValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
                                             ^
../src/unix/pty.cc:339:21: warning: 'IntegerValue' is deprecated: Use maybe version [-Wdeprecated-declarations]
  int fd = info[0]->IntegerValue();
                    ^
/Users/abubakar/.node-gyp/11.5.0/include/node/v8.h:2570:46: note: 'IntegerValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
                                             ^
../src/unix/pty.cc:342:26: warning: 'IntegerValue' is deprecated: Use maybe version [-Wdeprecated-declarations]
  winp.ws_col = info[1]->IntegerValue();
                         ^
/Users/abubakar/.node-gyp/11.5.0/include/node/v8.h:2570:46: note: 'IntegerValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
                                             ^
../src/unix/pty.cc:343:26: warning: 'IntegerValue' is deprecated: Use maybe version [-Wdeprecated-declarations]
  winp.ws_row = info[2]->IntegerValue();
                         ^
/Users/abubakar/.node-gyp/11.5.0/include/node/v8.h:2570:46: note: 'IntegerValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
                                             ^
../src/unix/pty.cc:369:21: warning: 'IntegerValue' is deprecated: Use maybe version [-Wdeprecated-declarations]
  int fd = info[0]->IntegerValue();
                    ^
/Users/abubakar/.node-gyp/11.5.0/include/node/v8.h:2570:46: note: 'IntegerValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
                                             ^
../src/unix/pty.cc:371:35: warning: 'ToString' is deprecated: Use maybe version [-Wdeprecated-declarations]
  String::Utf8Value tty_(info[1]->ToString());
                                  ^
/Users/abubakar/.node-gyp/11.5.0/include/node/v8.h:10248:22: note: 'ToString' has been explicitly marked deprecated here
Local<String> Value::ToString() const {
                     ^
../src/unix/pty.cc:371:21: warning: 'Utf8Value' is deprecated: Use Isolate version [-Wdeprecated-declarations]
  String::Utf8Value tty_(info[1]->ToString());
                    ^
/Users/abubakar/.node-gyp/11.5.0/include/node/v8.h:2992:28: note: 'Utf8Value' has been explicitly marked deprecated here
                  explicit Utf8Value(Local<v8::Value> obj));
                           ^
27 warnings and 1 error generated.
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/Cellar/node/11.5.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/wetty/node_modules/pty.js
gyp ERR! node -v v11.5.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pty.js@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Can someone please help in setup so that I can see its features.

**Comment by abubakar-bilal** [comment]
@krishnasrinivas ^

**Comment by butlerx** [comment]
the version of on npm is currently quite out of date and I'm unable to update it as only @krishnasrinivas was the key.

Could you pull from GitHub master and try against that

**Comment by koushikmln** [comment]
@butlerx can we have a new npm repo I could collaborate with you on this if you would like. I will update the readme to include setup instructions from repo instead of npm meanwhile.

**Comment by abubakar-bilal** [comment]
@butlerx @koushikmln Can you guys please guide me how to set it up on local from repo instead of npm. I currently have no idea how to run it on local from repo to see its working.

I would be really grateful to hear steps to run it on local from repo so that I can see this amazing terminal on my local if it fulfils my needs.

**Comment by koushikmln** [comment]
You can check the instructions from my fork -> [wetty](https://github.com/koushikmln/wetty)

**Comment by abubakar-bilal** [comment]
hey @koushikmln 

thanks so much for the help. I tried to clone and run `npm install` command but I got this error

```npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for express@^5.15.3
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'wetty.js'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/abubakar/.npm/_logs/2018-12-27T09_06_59_004Z-debug.log```

It would be best if I can reply today because I'm stuck here and I cannot proceed further. Thanks so much.

**Comment by koushikmln** [comment]
can you pull again? We just updated the repo with the new dependencies.

**Comment by abubakar-bilal** [comment]
hey @koushikmln I was able to setup locally with your fork. I've cloned your fork and I was able to setup locally.

Now when I run localhost:3000 it asks for user. And when I type my local user `abubakar` it says ssh localhost port 22 connection confused. 

I need to run it as my terminal in my browser. Is it necessary to run it as ssh to some other server.

**Comment by abubakar-bilal** [comment]
Hey @koushikmln 

I've set it up on my server with dns i.e. abc.com and I've root user with password `password` on that server. Now I need to access wetty on my browser. What I'm trying to do is 

http://abc.com:3000/ssh/root?sshpass=password

But it gives me this output

`abc.com login: ` and when I type root it gives me this error

`Login incorrect
abc.com login: `

I need your guidance to run it smoothly in browser because I want to autologin to my server and access terminal from browser given username `root` and password `password`.

Thank you in advance and thanks alot for guidance till now to setup successfully.

**Comment by koushikmln** [comment]
To use auto login, you need to run it as a non-root user. It won't work for
root user.

**Comment by abubakar-bilal** [comment]
@koushikmln thank you so much for this information. This really worked. But still when I type this url http://abc.com:3000/ssh/abubakar?sshpass=password

It asks for login and password and then it takes me to terminal. But I actually need to directly go to terminal when I hit url instead of manually enter username and password.

**Comment by koushikmln** [comment]
are you running the application as a non-root user too? Just using non-root
account won't work.

**Comment by abubakar-bilal** [comment]
ahh okay. so application also needs to be run as non root user. Sure, let me try that.

**Comment by abubakar-bilal** [comment]
@koushikmln I now started this application from `abubakar` user and hit above url in browser but it displays a button saying `reconnect` and this is the console output

```
disconnect
Mon Dec 31 2018 09:21:19 GMT+0000 (Coordinated Universal Time) Connection accepted.
Mon Dec 31 2018 09:21:19 GMT+0000 (Coordinated Universal Time) PID=14176 STARTED on behalf of user=abubakar@localhost
Mon Dec 31 2018 09:21:19 GMT+0000 (Coordinated Universal Time) PID=14176 ENDED
exit with code: 6
Error: Error: ioctl(2) failed.
Error: Error: ioctl(2) failed.
Error: Error: ioctl(2) failed.
Error: Error: ioctl(2) failed.
Error: Error: ioctl(2) failed.
Error: Error: ioctl(2) failed.
Error: Error: ioctl(2) failed.
Error: Error: ioctl(2) failed.```

**Comment by abubakar-bilal** [comment]
Thank you so much @koushikmln it worked finally. And it's really awesome. 👍

**Comment by danxtrate** [comment]
I cannot get it to work on Centos 7, I've tried both the original and the fork, this is the output: 

31217 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
31218 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
31219 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
31219 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
31219 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
31219 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
31220 verbose stack Error: node-pty@0.7.8 install: `node scripts/install.js`
31220 verbose stack Exit status 1
31220 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
31220 verbose stack     at emitTwo (events.js:126:13)
31220 verbose stack     at EventEmitter.emit (events.js:214:7)
31220 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
31220 verbose stack     at emitTwo (events.js:126:13)
31220 verbose stack     at ChildProcess.emit (events.js:214:7)
31220 verbose stack     at maybeClose (internal/child_process.js:915:16)
31220 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
31221 verbose pkgid node-pty@0.7.8
31222 verbose cwd /home/wetty/wetty
31223 verbose Linux 3.10.0-957.1.3.el7.x86_64
31224 verbose argv "/usr/bin/node" "/bin/npm" "install"
31225 verbose node v8.15.0
31226 verbose npm  v6.4.1
31227 error code ELIFECYCLE
31228 error errno 1
31229 error node-pty@0.7.8 install: `node scripts/install.js`
31229 error Exit status 1
31230 error Failed at the node-pty@0.7.8 install script.
31230 error This is probably not a problem with npm. There is likely additional logging output above.
31231 verbose exit [ 1, true ]
