### ISSUE TITLE
Install without yarn?

### ISSUE THREAD

**Issue by JamesNewton** [butlerx/wetty#200]
Is it possible to install without yarn? (trying to keep the size of my Ubuntu image as small as possible)

````
git clone https://github.com/krishnasrinivas/wetty
cd wetty
npm install
````
it appears to finish, but when I try to start it:
````
internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module './dist'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/srv/samba/share/www/wetty/index.js:5:15)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
root@localhost:/srv/samba/share/www/wetty#
````

OS is Ubuntu 16.04 running on Arm7.

**Comment by butlerx** [comment]
what version is in the package.json?

**Comment by ghost** [comment]
Same here. I'm using Oracle Linux 7.7 package.json version is 1.1.5

**Comment by truedat101** [comment]
Packaging step that's missing?

**Comment by JamesNewton** [comment]
I really wish I could get this installed so people could SSH into our open source robotic arm via the web interface.

**Comment by SyXuan** [comment]
Same here. package version 1.1.5

**Comment by truedat101** [comment]
> I really wish I could get this installed so people could SSH into our open source robotic arm via the web interface.

I was able to move forward with ttyd, which is a fork of tty.js.  It just works, but does require quite a bit more platform integration via linux packages and some libraries that need to be built.

**Comment by butlerx** [comment]
there is a issue on current version of node with node-pty can you try running ` yarn add node-pty@0.9.0-beta28` or `npm install node-pty@0.9.0-beta28` before running the rest of the setup and build and see if this fixes it

**Comment by SyXuan** [comment]
Same issue after `npm install node-pty@0.9.0-beta28`. It could not run from source code. But it running well from node_modules after `npm i wetty`.

**Comment by butlerx** [comment]
Could you please post error log when trying to install wetty

**Comment by JamesNewton** [comment]
SyXuan are you saying that you did `npm install node-pty@0.9.0-beta28` and tried to run wetty, and it failed, and then you did `npm i wetty` and then wetty would run? E.g. is it working for you now?

**Comment by yeyeto2788** [comment]
I hope this is still an issue, I got this error installing it globally:

```shell
yeyeto2788@orangepilite:~$ wetty --host 0.0.0.0 --port 3000
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /usr/local/lib/node_modules/wetty/node_modules/node-pty/lib/unixTerminal.js
- /usr/local/lib/node_modules/wetty/node_modules/node-pty/lib/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/wetty/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/wetty/node_modules/node-pty/lib/unixTerminal.js',
    '/usr/local/lib/node_modules/wetty/node_modules/node-pty/lib/index.js'
  ]
}
{"error":{"code":"MODULE_NOT_FOUND","requireStack":["/usr/local/lib/node_modules/wetty/node_modules/node-pty/lib/unixTerminal.js","/usr/local/lib/node_modules/wetty/node_modules/node-pty/lib/index.js"]},"level":"error","message":"uncaughtException: Cannot find module '../build/Release/pty.node'\nRequire stack:\n- /usr/local/lib/node_modules/wetty/node_modules/node-pty/lib/unixTerminal.js\n- /usr/local/lib/node_modules/wetty/node_modules/node-pty/lib/index.js\nError: Cannot find module '../build/Release/pty.node'\nRequire stack:\n- /usr/local/lib/node_modules/wetty/node_modules/node-pty/lib/unixTerminal.js\n- /usr/local/lib/node_modules/wetty/node_modules/node-pty/lib/index.js\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:725:27)\n    at Module.require (internal/modules/cjs/loader.js:952:19)\n    at require (internal/modules/cjs/helpers.js:88:18)\n    at Object.<anonymous> (/usr/local/lib/node_modules/wetty/node_modules/node-pty/lib/unixTerminal.js:26:11)\n    at Module._compile (internal/modules/cjs/loader.js:1063:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)\n    at Module.load (internal/modules/cjs/loader.js:928:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:769:14)\n    at Module.require (internal/modules/cjs/loader.js:952:19)","stack":"Error: Cannot find module '../build/Release/pty.node'\nRequire stack:\n- /usr/local/lib/node_modules/wetty/node_modules/node-pty/lib/unixTerminal.js\n- /usr/local/lib/node_modules/wetty/node_modules/node-pty/lib/index.js\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:725:27)\n    at Module.require (internal/modules/cjs/loader.js:952:19)\n    at require (internal/modules/cjs/helpers.js:88:18)\n    at Object.<anonymous> (/usr/local/lib/node_modules/wetty/node_modules/node-pty/lib/unixTerminal.js:26:11)\n    at Module._compile (internal/modules/cjs/loader.js:1063:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)\n    at Module.load (internal/modules/cjs/loader.js:928:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:769:14)\n    at Module.require (internal/modules/cjs/loader.js:952:19)","exception":true,"date":"Tue Nov 17 2020 17:00:38 GMT+0100 (Central European Standard Time)","process":{"pid":11749,"uid":1000,"gid":1000,"cwd":"/home/yeyeto2788","execPath":"/home/yeyeto2788/.nvm/versions/node/v14.15.1/bin/node","version":"v14.15.1","argv":["/home/yeyeto2788/.nvm/versions/node/v14.15.1/bin/node","/usr/local/bin/wetty","--host","0.0.0.0","--port","3000"],"memoryUsage":{"rss":36294656,"heapTotal":5935104,"heapUsed":4653656,"external":1699711,"arrayBuffers":101757}},"os":{"loadavg":[1.17,1.18,1.02],"uptime":115163},"trace":[{"column":15,"file":"internal/modules/cjs/loader.js","function":"Module._resolveFilename","line":880,"method":"_resolveFilename","native":false},{"column":27,"file":"internal/modules/cjs/loader.js","function":"Module._load","line":725,"method":"_load","native":false},{"column":19,"file":"internal/modules/cjs/loader.js","function":"Module.require","line":952,"method":"require","native":false},{"column":18,"file":"internal/modules/cjs/helpers.js","function":"require","line":88,"method":null,"native":false},{"column":11,"file":"/usr/local/lib/node_modules/wetty/node_modules/node-pty/lib/unixTerminal.js","function":null,"line":26,"method":null,"native":false},{"column":30,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":1063,"method":"_compile","native":false},{"column":10,"file":"internal/modules/cjs/loader.js","function":"Module._extensions..js","line":1092,"method":".js","native":false},{"column":32,"file":"internal/modules/cjs/loader.js","function":"Module.load","line":928,"method":"load","native":false},{"column":14,"file":"internal/modules/cjs/loader.js","function":"Module._load","line":769,"method":"_load","native":false},{"column":19,"file":"internal/modules/cjs/loader.js","function":"Module.require","line":952,"method":"require","native":false}],"label":"Wetty","timestamp":"2020-11-17T16:00:38.550Z"}
(node:11749) UnhandledPromiseRejectionWarning: Error: Cannot find module '../build/Release/pty.node'
Require stack:
- /usr/local/lib/node_modules/wetty/node_modules/node-pty/lib/unixTerminal.js
- /usr/local/lib/node_modules/wetty/node_modules/node-pty/lib/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/wetty/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11749) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11749) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Steps I followed:
* Install `nvm` for upgrade default node installed on Ubuntu 20.04.1
```shell
sudo apt install build-essential -y
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.0/install.sh | bash
```

* Restart terminal session.

* Upgrade node via `nvm` and install wetty:
```shell
nvm install v14.15.1
sudo npm install node-pty@0.9.0-beta28
sudo npm install -g wetty
wetty --host 0.0.0.0 --port 3000
```

**Comment by yeyeto2788** [comment]
Also installing it from source:

```shell
yeyeto2788@orangepilite:~$ cd workspace/wetty/
yeyeto2788@orangepilite:~/workspace/wetty$ npm install
npm WARN deprecated @types/winston@2.4.4: This is a stub types definition. winston provides its own type definitions, so you do not need this installed.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.

> husky@4.3.0 install /home/yeyeto2788/workspace/wetty/node_modules/husky
> node husky install

husky > Setting up git hooks
husky > Done

> node-pty@0.9.0 install /home/yeyeto2788/workspace/wetty/node_modules/node-pty
> node scripts/install.js

make: Entering directory '/home/yeyeto2788/workspace/wetty/node_modules/node-pty/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
../src/unix/pty.cc: In function ‘void pty_after_waitpid(uv_async_t*)’:
../src/unix/pty.cc:486:43: warning: ‘void* memset(void*, int, size_t)’ writing to an object of type ‘class Nan::Persistent<v8::Function>’ with no trivial copy-assignment [-Wclass-memaccess]
  486 |   memset(&baton->cb, -1, sizeof(baton->cb));
      |                                           ^
In file included from ../../nan/nan.h:405,
                 from ../src/unix/pty.cc:20:
../../nan/nan_persistent_12_inl.h:12:40: note: ‘class Nan::Persistent<v8::Function>’ declared here
   12 | template<typename T, typename M> class Persistent :
      |                                        ^~~~~~~~~~
In file included from ../../nan/nan.h:56,
                 from ../src/unix/pty.cc:20:
../src/unix/pty.cc: At global scope:
/home/yeyeto2788/.cache/node-gyp/14.15.1/include/node/node.h:758:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  758 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
/home/yeyeto2788/.cache/node-gyp/14.15.1/include/node/node.h:792:3: note: in expansion of macro ‘NODE_MODULE_X’
  792 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/unix/pty.cc:708:1: note: in expansion of macro ‘NODE_MODULE’
  708 | NODE_MODULE(pty, init)
      | ^~~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/pty.node
  COPY Release/pty.node
make: Leaving directory '/home/yeyeto2788/workspace/wetty/node_modules/node-pty/build'

> @fortawesome/fontawesome-common-types@0.2.32 postinstall /home/yeyeto2788/workspace/wetty/node_modules/@fortawesome/fontawesome-common-types
> node attribution.js

Font Awesome Free 0.2.32 by @fontawesome - https://fontawesome.com
License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)


> esbuild@0.8.9 postinstall /home/yeyeto2788/workspace/wetty/node_modules/esbuild
> node install.js

Unsupported platform: linux arm LE
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN @typescript-eslint/eslint-plugin@2.34.0 requires a peer of @typescript-eslint/parser@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/eslint-plugin@2.34.0 requires a peer of eslint@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! esbuild@0.8.9 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the esbuild@0.8.9 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/yeyeto2788/.npm/_logs/2020-11-17T16_20_27_630Z-debug.log
```

`package.json` version = `2.0.2`
