### ISSUE TITLE
Cannot install wetty with yarn global add wetty

### ISSUE THREAD

**Issue by abduramann** [butlerx/wetty#224]
**Describe the bug**
Cannot install wetty, I get the error below. I'm new to this context. Maybe I miss something. I just followed your documentation.

**Desktop (please complete the following information):**
- OS: Ubuntu 18.04
- Node: 8.10

**To Reproduce**
1. Run "yarn global add wetty"

**Result**
yarn global v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /home/abduraman/.config/yarn/global/node_modules/node-pty: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments: 
Directory: /home/abduraman/.config/yarn/global/node_modules/node-pty
Output:
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn node-gyp ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.

**Comment by janoskk** [comment]
I had the same issue. At the end I removed the `node` snap package and installed `nodejs` and `npm` from the universe and yarn with `npm`, and removed `~/.node.gyp`. After that the problem was solved.
```
rm -rf ~/.node-gyp
sudo apt install nodejs npm
sudo npm install --global yarn
```
