### ISSUE TITLE
nginx proxypass + custom domain crash on page load - errors in issue

### ISSUE THREAD

**Issue by userdocs** [butlerx/wetty#237]
**1:** If i load via `IP:PORT` it works as intended and does not crash.

**2:** If i load via my nginx + custom domain + lets encrypt + various ssl hardening tweaks (ssllabs a+) i get these errors below as soon as i load the page in a browser.

Note: I think it's related to my nginx setup but it's pretty standard SSL stuff (no TLS 1.0 or 1.1) but i can't see where. I have multiple other apps proxy passed with no issues.

Here are my errors: Any input or advice is welcome.

nginx error log (multiple occurrences of this error: (IP and domain redacted)

~~~
[error] 3572998#3572998: *1 connect() failed (111: Connection refused) while connecting to upstream, client: MYIP, server: domain.com, request: "GET /terminal/socket.io/?EIO=3&transport=polling&t=N2Mb7wI HTTP/2.0", upstream: "http://127.0.0.1:32546/terminal/socket.io/?EIO=3&transport=polling&t=N2Mb7wI", host: "domain.com"
~~~

The wetty app error (i have tried with `--bypasshelmet`

~~~javascript
{
   "error":{

   },
   "level":"\u001b[31merror\u001b[39m",
   "message":"uncaughtException: Cannot read property 'match' of undefined\nTypeError: Cannot read property 'match' of undefined\n    at O (/home/username/.node_apps/lib/node_modules/wetty/dist/index.js:1:2961)\n    at A (/home/username/.node_apps/lib/node_modules/wetty/dist/index.js:1:3920)\n    at Namespace.<anonymous> (/home/username/.node_apps/lib/node_modules/wetty/dist/index.js:1:6285)\n    at Namespace.emit (events.js:311:20)\n    at Namespace.emit (/home/username/.node_apps/lib/node_modules/wetty/node_modules/socket.io/lib/namespace.js:213:10)\n    at /home/username/.node_apps/lib/node_modules/wetty/node_modules/socket.io/lib/namespace.js:181:14\n    at processTicksAndRejections (internal/process/task_queues.js:79:11)",
   "stack":"TypeError: Cannot read property 'match' of undefined\n    at O (/home/username/.node_apps/lib/node_modules/wetty/dist/index.js:1:2961)\n    at A (/home/username/.node_apps/lib/node_modules/wetty/dist/index.js:1:3920)\n    at Namespace.<anonymous> (/home/username/.node_apps/lib/node_modules/wetty/dist/index.js:1:6285)\n    at Namespace.emit (events.js:311:20)\n    at Namespace.emit (/home/username/.node_apps/lib/node_modules/wetty/node_modules/socket.io/lib/namespace.js:213:10)\n    at /home/username/.node_apps/lib/node_modules/wetty/node_modules/socket.io/lib/namespace.js:181:14\n    at processTicksAndRejections (internal/process/task_queues.js:79:11)",
   "exception":true,
   "date":"Sun Mar 01 2020 23:32:15 GMT+0100 (Central European Standard Time)",
   "process":{
      "pid":3686608,
      "uid":1000,
      "gid":1000,
      "cwd":"/home/username",
      "execPath":"/usr/bin/node",
      "version":"v12.16.1",
      "argv":[
         "/usr/bin/node",
         "/home/username/.node_apps/bin/wetty",
         "--forcessh",
         "--sshkey",
         "/home/username/.ssh/wetty",
         "--sshuser",
         "username",
         "--sshport",
         "22",
         "--sshhost",
         "localhost",
         "--sshauth",
         "publickey",
         "--host",
         "127.0.0.1",
         "-p",
         "32546"
      ],
      "memoryUsage":{
         "rss":47951872,
         "heapTotal":12824576,
         "heapUsed":10893416,
         "external":1937183
      }
   },
   "os":{
      "loadavg":[
         0.18603515625,
         0.1748046875,
         0.15283203125
      ],
      "uptime":906993
   },
   "trace":[
      {
         "column":2961,
         "file":"/home/username/.node_apps/lib/node_modules/wetty/dist/index.js",
         "function":"O",
         "line":1,
         "method":null,
         "native":false
      },
      {
         "column":3920,
         "file":"/home/username/.node_apps/lib/node_modules/wetty/dist/index.js",
         "function":"A",
         "line":1,
         "method":null,
         "native":false
      },
      {
         "column":6285,
         "file":"/home/username/.node_apps/lib/node_modules/wetty/dist/index.js",
         "function":null,
         "line":1,
         "method":null,
         "native":false
      },
      {
         "column":20,
         "file":"events.js",
         "function":"Namespace.emit",
         "line":311,
         "method":"emit",
         "native":false
      },
      {
         "column":10,
         "file":"/home/username/.node_apps/lib/node_modules/wetty/node_modules/socket.io/lib/namespace.js",
         "function":"Namespace.emit",
         "line":213,
         "method":"emit",
         "native":false
      },
      {
         "column":14,
         "file":"/home/username/.node_apps/lib/node_modules/wetty/node_modules/socket.io/lib/namespace.js",
         "function":null,
         "line":181,
         "method":null,
         "native":false
      },
      {
         "column":11,
         "file":"internal/process/task_queues.js",
         "function":"processTicksAndRejections",
         "line":79,
         "method":null,
         "native":false
      }
   ],
   "label":"Wetty",
   "timestamp":"2020-03-01T22:32:15.611Z"
}
~~~

**Comment by antonyjim** [comment]
The issue is most likely related to your nginx conf file for that domain but we can't know without seeing it. Make sure you are passing the `Upgrade` header in your location block. It should look something like this:

```
server {
        listen 8443 ssl;
        listen [::]:8443 ssl;

        ssl_certificate /etc/letsencrypt/live/ssh.mydomain.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/ssh.mydomain.com/privkey.pem;
        include /etc/letsencrypt/options-ssl-nginx.conf;
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

        server_name ssh.ssh.mydomain.com;

        root /var/www/wetty;

        location / {
                proxy_pass http://127.0.0.1:8000;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
        }

}
```

**Comment by userdocs** [comment]
Turns out it was this particular line:

~~~
add_header Referrer-Policy no-referrer always;
~~~

Seem like that was causing the null value error and causing the app to close?

Any recommendations on an alternative setting? https://scotthelme.co.uk/a-new-security-header-referrer-policy/

It seems to work OK with this setting.

~~~
add_header Referrer-Policy same-origin always;
~~~

**Comment by 2sheds** [comment]
I'm trying to make WeTTY available behind a cloud reverse proxy (ZyXEL's KeenDNS service) which strips Referer header. WeTTY dies with the same error in `server/command/address.ts` because it can't parse referer. The only reason it needs to is to extract the SSH username from the URL:
> go to `http://yourserver:3000/wetty/ssh/<username>` to specify the user before hand.

Respectfully, this [pattern of Express stripping known `/ssh/` suffix from base URL](https://github.com/butlerx/wetty/blob/master/src/server/socketServer/html.ts#L7) and then making socketServer [rely on second-hand knowledge in the form of an HTTP header to get to the same value](https://github.com/butlerx/wetty/blob/master/src/server/command/index.ts#L16) looks like it's built to fail: it's delegating responsibility to relay crucial datapoint (username) from one component (Express) to another (socketServer) to external actors (browser and upstream proxy) which may not always be possible to control (like in my case).

*EDIT*: What makes this even more fragile, is that when the value of referer is unknown, the app just crashes - perhaps it would be safer to assume that "missing referer" equals "no username specified" and just do the user prompt as per default?
