### ISSUE TITLE
Problems with Wetty after upgrade

### ISSUE THREAD

**Issue by lozbrown** [butlerx/wetty#267]
Hi

After upgrading to ubuntu Focal Fossa wetty wont start..

```
loz@gravity:~$ wetty
internal/modules/cjs/loader.js:807
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/usr/local/lib/node_modules/wetty/node_modules/pty.js/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/wetty/node_modules/pty.js/lib/pty.js:9:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```

I've tried all of the following commands to resolve this to no avail
yarn global add wetty
sudo npm install -g npm
npm rebuild
npm rebuild wetty
yarn rebuild wetty
yarn rebuild
sudo yarn rebuild
yarn global rebuild
yarn global upgrade

any suggestions how to fix this?

**Comment by lozbrown** [comment]
tried removeing and reinstalling wetty now i get this 

oz@gravity:~$ sudo yarn global add wetty
yarn global v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /usr/local/share/.config/yarn/global/node_modules/node-pty: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments:
Directory: /usr/local/share/.config/yarn/global/node_modules/node-pty
Output:
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn node-gyp ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.

**Comment by butlerx** [comment]
This appears to be an issue with the dependency  node-pty which uses c bindings and likely needs to be recompiled post upgrade.

**Comment by lozbrown** [comment]
unistalled and re-installed node to transfer this
