### ISSUE TITLE
TypeError: Parameter "url" must be a string, not undefined

### ISSUE THREAD

**Issue by kmlucy** [butlerx/wetty#310]
**Describe the bug**
When trying to connect to Wetty, I get the logs below and the application crashes. 

**To Reproduce**
1. Install from Docker container 
2. Reverse proxy via Nginx 
3. Navigate to URL

**Expected behavior**
App doesn't crash. 

**Desktop**
 - OS: Windows 10 1903
 - Browser: Chrome 87.0.4280.88

**Logs**
```
info: HTTP GET /wetty {"meta":{"req":{"url":"/wetty","headers":{"host":"<URL>","x-real-ip":"<IP>","x-forwarded-for":"<IP>","x-forwarded-host":"<URL>","x-forwarded-proto":"https","x-forwarded-ssl":"on","x-forwarded-port":"443","x-forwarded-server":"<URL>","x-scheme":"https","connection":"upgrade","upgrade-insecure-requests":"1","dnt":"1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","sec-fetch-site":"same-origin","sec-fetch-mode":"navigate","sec-fetch-user":"?1","sec-fetch-dest":"document","sec-ch-ua":"\"Google Chrome\";v=\"87\", \" Not;A Brand\";v=\"99\", \"Chromium\";v=\"87\"","sec-ch-ua-mobile":"?0","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9","cookie":"_ga=<TOKEN>; experimentation_subject_id=<TOKEN>; sidebar_collapsed=false; csrftoken=<TOKEN>; __utma=<TOKEN>; oauth2=<TOKEN>; io=<TOKEN>; XSRF-TOKEN=<TOKEN>; heimdall_session=<TOKEN>","if-none-match":"<TOKEN>"},"method":"GET","httpVersion":"1.1","originalUrl":"/wetty","query":{}},"res":{"statusCode":304},"responseTime":6},"label":"Wetty","timestamp":"2021-01-05T18:21:38.171Z"}
info: HTTP GET /wetty/public/index.css {"meta":{"req":{"url":"/wetty/public/index.css","headers":{"host":"<URL>","x-real-ip":"<IP>","x-forwarded-for":"<IP>","x-forwarded-host":"<URL>","x-forwarded-proto":"https","x-forwarded-ssl":"on","x-forwarded-port":"443","x-forwarded-server":"<URL>","x-scheme":"https","connection":"upgrade","sec-ch-ua":"\"Google Chrome\";v=\"87\", \" Not;A Brand\";v=\"99\", \"Chromium\";v=\"87\"","dnt":"1","sec-ch-ua-mobile":"?0","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36","accept":"text/css,*/*;q=0.1","sec-fetch-site":"same-origin","sec-fetch-mode":"no-cors","sec-fetch-dest":"style","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9","cookie":"_ga=<TOKEN>; experimentation_subject_id=<TOKEN>; sidebar_collapsed=false; csrftoken=<TOKEN>; __utma=<TOKEN>; oauth2=<TOKEN>; io=<TOKEN>; XSRF-TOKEN=<TOKEN>; heimdall_session=<TOKEN>","if-none-match":"<TOKEN>","if-modified-since":"Sat, 08 Aug 2020 08:12:19 GMT"},"method":"GET","httpVersion":"1.1","originalUrl":"/wetty/public/index.css","query":{}},"res":{"statusCode":304},"responseTime":5},"label":"Wetty","timestamp":"2021-01-05T18:21:38.214Z"}
info: HTTP GET /wetty/public/index.js {"meta":{"req":{"url":"/wetty/public/index.js","headers":{"host":"<URL>","x-real-ip":"<IP>","x-forwarded-for":"<IP>","x-forwarded-host":"<URL>","x-forwarded-proto":"https","x-forwarded-ssl":"on","x-forwarded-port":"443","x-forwarded-server":"<URL>","x-scheme":"https","connection":"upgrade","sec-ch-ua":"\"Google Chrome\";v=\"87\", \" Not;A Brand\";v=\"99\", \"Chromium\";v=\"87\"","dnt":"1","sec-ch-ua-mobile":"?0","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36","accept":"*/*","sec-fetch-site":"same-origin","sec-fetch-mode":"no-cors","sec-fetch-dest":"script","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9","cookie":"_ga=<TOKEN>; experimentation_subject_id=<TOKEN>; sidebar_collapsed=false; csrftoken=<TOKEN>; __utma=<TOKEN>; oauth2=<TOKEN>; io=<TOKEN>; XSRF-TOKEN=<TOKEN>; heimdall_session=<TOKEN>","if-none-match":"<TOKEN>","if-modified-since":"Sat, 08 Aug 2020 08:12:19 GMT"},"method":"GET","httpVersion":"1.1","originalUrl":"/wetty/public/index.js","query":{}},"res":{"statusCode":304},"responseTime":1},"label":"Wetty","timestamp":"2021-01-05T18:21:38.217Z"}
info: Connection accepted. {"label":"Wetty","timestamp":"2021-01-05T18:21:38.306Z"}
error: uncaughtException: Parameter "url" must be a string, not undefined
TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:103:11)
    at Object.urlParse [as parse] (url.js:97:13)
    at urlArgs (/app/dist/index.js:153:192)
    at module.exports../src/server/command/index.ts.__webpack_exports__.default (/app/dist/index.js:153:568)    at Namespace.io.on.socket (/app/dist/index.js:383:166)
    at emitOne (events.js:116:13)
    at Namespace.emit (events.js:211:7)
    at Namespace.emit (/app/node_modules/socket.io/lib/namespace.js:213:10)
    at /app/node_modules/socket.io/lib/namespace.js:181:14
    at _combinedTickCallback (internal/process/next_tick.js:132:7) {"error":{},"stack":"TypeError: Parameter \"url\" must be a string, not undefined\n    at Url.parse (url.js:103:11)\n    at Object.urlParse [as parse] (url.js:97:13)\n    at urlArgs (/app/dist/index.js:153:192)\n    at module.exports../src/server/command/index.ts.__webpack_exports__.default (/app/dist/index.js:153:568)\n    at Namespace.io.on.socket (/app/dist/index.js:383:166)\n    at emitOne (events.js:116:13)\n    at Namespace.emit (events.js:211:7)\n    at Namespace.emit (/app/node_modules/socket.io/lib/namespace.js:213:10)\n    at /app/node_modules/socket.io/lib/namespace.js:181:14\n    at _combinedTickCallback (internal/process/next_tick.js:132:7)","exception":true,"date":"Tue Jan 05 2021 18:21:38 GMT+0000 (UTC)","process":{"pid":19,"uid":1000,"gid":1000,"cwd":"/app","execPath":"/usr/local/bin/node","version":"v8.17.0","argv":["/usr/local/bin/node","/app","-p","3000","--sshhost","<URL>","--sshport","22","--base","/wetty/","--sshuser","<USER>","--sshauth","publickey","--sshkey","/config/id_rsa"],"memoryUsage":{"rss":42938368,"heapTotal":19644416,"heapUsed":15861240,"external":25019}},"os":{"loadavg":[1.88037109375,1.8935546875,2.14453125],"uptime":2510254},"trace":[{"column":11,"file":"url.js","function":"Url.parse","line":103,"method":"parse","native":false},{"column":13,"file":"url.js","function":"Object.urlParse [as parse]","line":97,"method":"urlParse [as parse]","native":false},{"column":192,"file":"/app/dist/index.js","function":"urlArgs","line":153,"method":null,"native":false},{"column":568,"file":"/app/dist/index.js","function":"module.exports../src/server/command/index.ts.__webpack_exports__.default","line":153,"method":"default","native":false},{"column":166,"file":"/app/dist/index.js","function":"Namespace.io.on.socket","line":383,"method":"socket","native":false},{"column":13,"file":"events.js","function":"emitOne","line":116,"method":null,"native":false},{"column":7,"file":"events.js","function":"Namespace.emit","line":211,"method":"emit","native":false},{"column":10,"file":"/app/node_modules/socket.io/lib/namespace.js","function":"Namespace.emit","line":213,"method":"emit","native":false},{"column":14,"file":"/app/node_modules/socket.io/lib/namespace.js","function":null,"line":181,"method":null,"native":false},{"column":7,"file":"internal/process/next_tick.js","function":"_combinedTickCallback","line":132,"method":null,"native":false}],"label":"Wetty","timestamp":"2021-01-05T18:21:38.310Z"}
error: uncaughtException: Parameter "url" must be a string, not undefined
TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:103:11)
    at Object.urlParse [as parse] (url.js:97:13)
    at urlArgs (/app/dist/index.js:153:192)
    at module.exports../src/server/command/index.ts.__webpack_exports__.default (/app/dist/index.js:153:568)    at Namespace.io.on.socket (/app/dist/index.js:383:166)
    at emitOne (events.js:116:13)
    at Namespace.emit (events.js:211:7)
    at Namespace.emit (/app/node_modules/socket.io/lib/namespace.js:213:10)
    at /app/node_modules/socket.io/lib/namespace.js:181:14
    at _combinedTickCallback (internal/process/next_tick.js:132:7) {"error":{},"stack":"TypeError: Parameter \"url\" must be a string, not undefined\n    at Url.parse (url.js:103:11)\n    at Object.urlParse [as parse] (url.js:97:13)\n    at urlArgs (/app/dist/index.js:153:192)\n    at module.exports../src/server/command/index.ts.__webpack_exports__.default (/app/dist/index.js:153:568)\n    at Namespace.io.on.socket (/app/dist/index.js:383:166)\n    at emitOne (events.js:116:13)\n    at Namespace.emit (events.js:211:7)\n    at Namespace.emit (/app/node_modules/socket.io/lib/namespace.js:213:10)\n    at /app/node_modules/socket.io/lib/namespace.js:181:14\n    at _combinedTickCallback (internal/process/next_tick.js:132:7)","exception":true,"date":"Tue Jan 05 2021 18:21:38 GMT+0000 (UTC)","process":{"pid":19,"uid":1000,"gid":1000,"cwd":"/app","execPath":"/usr/local/bin/node","version":"v8.17.0","argv":["/usr/local/bin/node","/app","-p","3000","--sshhost","<URL>","--sshport","22","--base","/wetty/","--sshuser","<USER>","--sshauth","publickey","--sshkey","/config/id_rsa"],"memoryUsage":{"rss":42938368,"heapTotal":19644416,"heapUsed":15941608,"external":25043}},"os":{"loadavg":[1.88037109375,1.8935546875,2.14453125],"uptime":2510254},"trace":[{"column":11,"file":"url.js","function":"Url.parse","line":103,"method":"parse","native":false},{"column":13,"file":"url.js","function":"Object.urlParse [as parse]","line":97,"method":"urlParse [as parse]","native":false},{"column":192,"file":"/app/dist/index.js","function":"urlArgs","line":153,"method":null,"native":false},{"column":568,"file":"/app/dist/index.js","function":"module.exports../src/server/command/index.ts.__webpack_exports__.default","line":153,"method":"default","native":false},{"column":166,"file":"/app/dist/index.js","function":"Namespace.io.on.socket","line":383,"method":"socket","native":false},{"column":13,"file":"events.js","function":"emitOne","line":116,"method":null,"native":false},{"column":7,"file":"events.js","function":"Namespace.emit","line":211,"method":"emit","native":false},{"column":10,"file":"/app/node_modules/socket.io/lib/namespace.js","function":"Namespace.emit","line":213,"method":"emit","native":false},{"column":14,"file":"/app/node_modules/socket.io/lib/namespace.js","function":null,"line":181,"method":null,"native":false},{"column":7,"file":"internal/process/next_tick.js","function":"_combinedTickCallback","line":132,"method":null,"native":false}],"label":"Wetty","timestamp":"2021-01-05T18:21:38.310Z"}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wetty@1.3.2 start: `node . "-p" "3000" "--sshhost" "<URL>" "--sshport" "22" "--base" "/wetty/" "--sshuser" "<USER>" "--sshauth" "publickey" "--sshkey" "/config/id_rsa"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wetty@1.3.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2021-01-05T18_21_41_321Z-debug.log
```

**Comment by butlerx** [comment]
can you paste the command you are running?

**Comment by kmlucy** [comment]
I am using the `svenihoney/wetty` Docker image, so this should be the generated command:
```
npm start -- -p 3000 --sshhost <URL> --sshport 22 --base /wetty/ --sshuser <USER> --sshauth publickey --knownhosts /config/known_hosts --sshkey /config/id_rsa
```

This is what shows in the logs:
```
node . "-p" "3000" "--sshhost" "<URL>" "--sshport" "22" "--base" "/wetty/" "--sshuser" "<USER>" "--sshauth" "publickey" "--sshkey" "/config/id_rsa"
```
