### ISSUE TITLE
not able to run node app.js -p 3000

### ISSUE THREAD

**Issue by cneira** [butlerx/wetty#66]
I'm using  Node version 5.11.1 

Error stack : 

Module.js:341
    throw err;
    ^

Error: Cannot find module '../build/Release/pty.node'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/wetty/node_modules/pty.js/lib/pty.js:9:11)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

**Comment by imuli** [comment]
Did you run `npm install` first?

**Comment by cneira** [comment]
Yes, I did wetty is working perfect in FreeBSD 10.3 but using linux gives
me this error following the same steps from the documentation

**Comment by cneira** [comment]
needed to recompile pty.js that fixed the issue.
